config/routes.rb
Rails.application.routes.draw do
  root to: 'vista#index'
  

resources :usuarios
root 'usuarios#index'

resources :establecimientos
root 'establecimientos#index'

resources :platillos
root 'platillos#index'

resources :reservas
root 'reservas#index'
  
resources :tareas  do
  member do
    get 'Ver'
 	  get 'Query1'
    get 'Query2'
    get 'Query3'
    get 'Query4'
  end
  collection do
    get 'Ver'
    get 'Query1'
    get 'Query2'
    get 'Query3'
    get 'Query4'
  end
end

resources :tareas
root 'tareas#index'

resources :alergias
root 'alergias#index'

resources :telefonos
root 'telefonos#index'

resources :establecimientos
root 'establecimientos#index'

resources :ordenes
root 'ordenes#index'

resources :alergias
root 'alergias#index'

resources :vista
root 'vista#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/application_controller_helper.rb
module ApplicationControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_helper_helper.rb
module ApplicationHelperHelper
end

app/helpers/establecimientos_controller_helper.rb
module EstablecimientosControllerHelper
end

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/establecimientos/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>
</center>
	
<body>

<article>
<center>
<section>

<h2><em>Establecimiento a Modificar</em></h2>

	<div class="center">
	<%= render 'form', establecimiento: @establecimiento %>
	</div>
	<br>
    <div class="relative">
    <center><%= link_to 'Volver', establecimientos_path %> o <%= link_to 'Mostrar', @establecimiento %> </center>
    </div>

</section>
</center>
</article>

<footer>
  <center><em>Le agradecemos que se tome un momento para actualizar su informacion, sino no podriamos ofrecerle el mejor servicio</em></center>
</footer>

</body>
</html>

app/views/establecimientos/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>
<body>

<p id="notice"><%= notice %></p>

  <br />
<article>
<section>
<h2><em>Establecimientos Registrados</em></h2>
<center>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Especialidad</th>
      <th>Email</th>
      <th>Calificacion</th>
      <th>Direccion</th>
      <th>RIF</th>
      <th>Telefono</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @establecimientos.each do |establecimiento| %>
      <tr>
        <td><%= establecimiento.nombre %></td>
        <td><%= establecimiento.especialidad %></td>
        <td><%= establecimiento.email %></td>
        <td><%= establecimiento.calificacion %></td>
        <td><%= establecimiento.direccion %></td>
        <td><%= establecimiento.rif %></td>
        <td><%= establecimiento.telefono %></td>
        <td><%= link_to 'Mostar', establecimiento %></td>
        <td><%= link_to 'Editar', edit_establecimiento_path(establecimiento) %></td>
        <td><%= link_to 'Destruir', establecimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center>
<br>
    <div class="relative">
    <center><%= link_to 'Registrar', new_establecimiento_path %></center>
    </div>
</section>
</article>

<footer>
  <center><em>Restaurantes disponibles</em></center>
</footer>

</body>
</html>

app/views/establecimientos/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>

<body>

<p id="notice"><%= notice %></p>



<article>
  <center>
<section>

<h2><em>Establecimiento Solicitado</em></h2>

<div class ="center">
<p>
  <strong>Nombre:</strong>
  <%= @establecimiento.nombre %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @establecimiento.especialidad %>
</p>

<p>
  <strong>Email:</strong>
  <%= @establecimiento.email %>
</p>

<p>
  <strong>Calificacion:</strong>
  <%= @establecimiento.calificacion %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @establecimiento.direccion %>
</p>

<p>
  <strong>RIF:</strong>
  <%= @establecimiento.rif %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @establecimiento.telefono %>
</p>

</div>
<br>
    <div class="relative">
    <center> <%= link_to 'Volver', establecimientos_path %> o <%= link_to 'Editar', edit_establecimiento_path(@establecimiento) %>
    </center>
    </div>
</section>
</center>
</article>

<footer>
  <center><em>Aqui esta el establecimiento que usted solicito</em></center>
</footer>

</body>
</html>


app/views/ordenes/_form.html.erb
<%= form_for(orden) do |f| %>
  <% if orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden.errors.count, "error") %> prohibited this orden from being saved:</h2>

      <ul>
      <% orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha %>
    <%= f.text_field :fecha %>
  </div>
  
  <div class="field">
    <%= f.label :Hora %>
    <%= f.text_field :hora %>
  </div>


  <div class="field">
    <%= f.label :Estado %>
    <%= f.text_field :estado %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/platillos/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>

<body>

<p id="notice"><%= notice %></p>


<article>
<section>
<h2><em>platillos Registrados</em></h2>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ingredientes</th>
      <th>Precio</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.ingrediente %></td>
        <td><%= platillo.precio %></td>

        <td><%= link_to 'Mostar', platillo %></td>
        <td><%= link_to 'Editar', edit_platillo_path(platillo) %></td>
        <td><%= link_to 'Destruir', platillo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
    <div class="relative">
    <center><%= link_to 'Registrar', new_platillo_path %></center>
    </div>
</section>
</article>

<footer>
  <center><em>Platillos disponibles</em></center>
</footer>

</body>
</html>

app/views/platillos/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>
</center>
<body>



<article>

<body>

<p id="notice"><%= notice %></p>

<header>

</header>

<article>
<section>

<h2><em>Platillo Solicitado</em></h2>

<div class ="center">
<p>
  <strong>Nombre:</strong>
  <%= @platillo.nombre %>
</p>

<p>
  <strong>Ingredientes:</strong>
  <%= @platillo.ingrediente %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @platillo.precio %>
</p>

</div>
<br>
    <div class="relative">
    <center> <%= link_to 'Volver', platillos_path %> o <%= link_to 'Editar', edit_platillo_path(@platillo) %>
    </center>
    </div>
</section>
</article>

<footer>
  <center><em>Aqui esta el platillo que usted solicito</em></center>
</footer>

</body>
</html>

app/views/reservas/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>

<body>

<p id="notice"><%= notice %></p>



<article>
<section>
<h2><em>Reservas Registradas</em></h2>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Estado</th>

      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.fecha %></td>
        <td><%= reserva.hora %></td>
        <td><%= reserva.estado %></td>
        <td><%= link_to 'Mostar', reserva %></td>
        <td><%= link_to 'Editar', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destruir', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
    <div class="relative">
    <center><%= link_to 'Registrar', new_reserva_path %></center>
    </div>
</section>
</article>

<footer>
  <center><em>Reservaciones </em></center>
</footer>

</body>
</html>

app/views/reservas/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>
-->

 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="busca#index" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="usuario#show" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>
<body>

<p id="notice"><%= notice %></p>

<header>
<h1><center>FINDDISH<center></h1>
</header>

<article>
<section>

<h2><em>Reserva Solicitada</em></h2>

<div class ="center">
<p>
  <strong>Fecha:</strong>
  <%= @reserva.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @reserva.hora %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @reserva.estado %>
</p>


</div>
<br>
    <div class="relative">
    <center> <%= link_to 'Volver', reservas_path %> o <%= link_to 'Editar', edit_reserva_path(@reserva) %>
    </center>
    </div>
</section>
</article>

<footer>
  <center><em>Aqui esta la reserva que usted solicito, le pedimos que no de un mal uso a esta informacion</em></center>
</footer>

</body>
</html>