FindDish/config/routes.rb
Rails.application.routes.draw do
root to: 'vista#index'
resources :usuarios
root 'usuarios#index'

resources :establecimientos
root 'establecimientos#index'

resources :platillos
root 'platillos#index'

resources :reservas
root 'reservas#index'

resources :tareas  do
  member do
    get 'Ver'
 	  get 'Query1'
    get 'Query2'
    get 'Query3'
    get 'Query4'
  end
  collection do
    get 'Ver'
    get 'Query1'
    get 'Query2'
    get 'Query3'
    get 'Query4'
  end
end

resources :tareas
root 'tareas#index'

resources :alergias
root 'alergias#index'

resources :telefonos
root 'telefonos#index'

resources :establecimientos
root 'establecimientos#index'

resources :ordenes
root 'ordenes#index'

resources :alergias
root 'alergias#index'

resources :tareas
root 'tareas#index'

resources :vista
root 'vista#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

FindDish/app/views/platillos/_form.html.erb
<%= form_for(platillo) do |f| %>
  <% if platillo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(platillo.errors.count, "error") %> prohibited this platillo from being saved:</h2>

      <ul>
      <% platillo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :ingrediente %>
    <%= f.text_field :ingrediente %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.number_field :precio %>
  </div>

   <div class="field">
   
    <%= f.association :establecimiento %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FindDish/app/views/platillos/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>
	
	
	
<body>


<article>

<section>
<h2><em>Platillo a Modificar</em></h2>

	<div class="center">
	<%= render 'form', platillo: @platillo %>
	</div>
	<br>
    <div class="relative">
    <center><%= link_to 'Volver', platillos_path %> o <%= link_to 'Mostrar', @platillo %> </center>
    </div>

</section>
</article>

<footer>
  <center><em>Platillos</em></center>
</footer>

</body>
</html>

FindDish/app/views/platillos/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>

<body>

<p id="notice"><%= notice %></p>


<article>
<section>
<h2><em>platillos Registrados</em></h2>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ingredientes</th>
      <th>Precio</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @platillos.each do |platillo| %>
      <tr>
        <td><%= platillo.nombre %></td>
        <td><%= platillo.ingrediente %></td>
        <td><%= platillo.precio %></td>

        <td><%= link_to 'Mostar', platillo %></td>
        <td><%= link_to 'Editar', edit_platillo_path(platillo) %></td>
        <td><%= link_to 'Destruir', platillo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
    <div class="relative">
    <center><%= link_to 'Registrar', new_platillo_path %></center>
    </div>
</section>
</article>

<footer>
  <center><em>Platillos disponibles</em></center>
</footer>

</body>
</html>

FindDish/app/views/platillos/new.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>
<body>



<article>

<section>
<h2><em>Platillo Nuevo</em></h2>

	<div class="center">
	<%= render 'form', platillo: @platillo %>
	</div>
	<br>
    <div class="relative">
    <center><%= link_to 'Volver', platillos_path %></center>
    </div>

</section>
</article>

<footer>
  <center><em>Esta a un click de encontrar sus platillos favoritos en segundos, no hay nada que perder mas que el antojo</em></center>
</footer>



</body>
</html>

FindDish/app/views/platillos/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>
<body>



<article>

<body>

<p id="notice"><%= notice %></p>

<header>

</header>

<article>
<section>

<h2><em>Platillo Solicitado</em></h2>

<div class ="center">
<p>
  <strong>Nombre:</strong>
  <%= @platillo.nombre %>
</p>

<p>
  <strong>Ingredientes:</strong>
  <%= @platillo.ingrediente %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @platillo.precio %>
</p>

</div>
<br>
    <div class="relative">
    <center> <%= link_to 'Volver', platillos_path %> o <%= link_to 'Editar', edit_platillo_path(@platillo) %>
    </center>
    </div>
</section>
</article>

<footer>
  <center><em>Aqui esta el platillo que usted solicito</em></center>
</footer>

</body>
</html>

FindDish/app/views/usuarios/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>

<body>



<article>

<section>
<h2><em>Usuario a Modificar</em></h2>

	<div class="center">
	<%= render 'form', usuario: @usuario %>
	</div>
	<br>
    <div class="relative">
    <center><%= link_to 'Volver', usuarios_path %> o <%= link_to 'Mostrar', @usuario %> </center>
    </div>

</section>
</article>

<footer>
  <center><em>Le agradecemos que se tome un momento para actualizar su informacion, sino no podriamos ofrecerle el mejor servicio</em></center>
</footer>

</body>
</html>



FindDish/app/views/usuarios/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>


<body>

<p id="notice"><%= notice %></p>



<article>
<section>
<h2><em>Usuarios Registrados</em></h2>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Cedula</th>
      <th>Numero</th>
      <th>Email</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.cedula %></td>
        <td><%= usuario.numero %></td>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Mostar', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destruir', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
    <div class="relative">
    <center><%= link_to 'Registrarse', new_usuario_path %></center>
    </div>
</section>
</article>

<footer>
  <center><em>Estas personas ya estan encontrando sus platillos favoritos con nosotros. Presiona "Registrarse" y unete a ellos</em></center>
</footer>

</body>
</html>

FindDish/app/views/usuarios/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.myButton {
  -moz-box-shadow:inset 0px 39px 0px -24px #e67a73;
  -webkit-box-shadow:inset 0px 39px 0px -24px #e67a73;
  box-shadow:inset 0px 39px 0px -24px #e67a73;
  background-color:#e4685d;
  display:inline-block;
  cursor:pointer;
  color:#ffffff;
  font-family:Arial;
  font-size:15px;
  padding:10px 34px;
  text-decoration:none;
  text-shadow:0px 1px 0px #b23e35;

}
.myButton:hover {
  background-color:#eb675e;
}
.myButton:active {
  position:relative;
  top:1px;
}

.busca {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  width: 350px;
  height: 5px;
  margin: 18px;
  padding: 10px 20px;
  overflow: hidden;
  border: 1px solid #b7b7b7;
  -webkit-border-radius: 12px;
  border-radius: 12px;
  font: normal 16px/normal "Times New Roman", Times, serif;
  color: rgba(0,142,198,1);
  -o-text-overflow: clip;
  text-overflow: clip;
  background: rgba(252,252,252,1);
  -webkit-box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  box-shadow: 2px 2px 2px 0 rgba(0,0,0,0.2) inset;
  text-shadow: 1px 1px 0 rgba(255,255,255,0.66) ;
  -webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  -o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
  transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}



</style>
  <br />
<link href="/style.css" type="text/css" rel=stylesheet>
<title>FindDish</title>
</head>
<!-- LOGO -->
<center>
<img src="http://fotos.fotoflexer.com/c602ad9b29403b4b0112341909860429.jpg" alt="FindDish Logo" >
</center>
<!-- BUSQUEDA -->

  <br />
  <center>
<input class="busca" placeholder="Buscar" />
</center>


 <!-- BOTONES -->
<center>
<a href="vista#index" class="myButton">Home</a>
<a href="#" class="myButton">Buscar</a>
<a href="establecimientos#index" class="myButton">Establecimientos</a>
<a href="#" class="myButton">Contacto</a>
<a href="#" class="myButton">Mi Perfil</a>
<a href="tareas#index" class="myButton">Tarea</a>

</center>



<body>

<p id="notice"><%= notice %></p>


<article>
<section>

<h2><em>Usuario Solicitado</em></h2>

<div class ="center">
<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @usuario.cedula %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @usuario.numero %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>
</div>
<br>
    <div class="relative">
    <center> <%= link_to 'Volver', usuarios_path %> o <%= link_to 'Editar', edit_usuario_path(@usuario) %>
    </center>
    </div>
</section>
</article>

<footer>
  <center><em>Aqui esta el usuario que usted solicito, le pedimos que no de un mal uso a esta informacion</em></center>
</footer>

</body>
</html>